apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "luxe-admin.fullname" . }}
spec:
  secretStoreRef:
    name: clustersecretstore-tera
    kind: ClusterSecretStore
  refreshInterval: '1m'
  target:
    name: admin
  dataFrom:
    - extract:
        key: 'staging/admin'
